### ISSUE TITLE
[Bug]: Double click on the same tab [CodingPlateform] content does not displays.

### ISSUE THREAD

**Issue by Aayushraj22** [Yash-Parsana/CrazyCoderWebApp#22] opened 2024-05-11 18:52 UTC
**Problem**
On selecting any coding-platform-name its data gets display but on clicking the same platform again nothing loads.

**To Reproduce**
1. Go to home
2. Click on any plateform **[suppose codeforces]**, it data fetched and displays.
3. Again click on the same button, nothing loads.

**Solution**
On again clicking the same button it should display the same data.

**Screenshot**
![Screenshot (70)](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/97510973/22713078-0290-43f8-b0fd-972b315ef579)

**Comment by MishraTanishq619** [comment] 2024-05-12 15:30
I can work on this, but i required '.env.example' file to run development server.

**Comment by Aayushraj22** [comment] 2024-05-13 20:57
@Yash-Parsana Please Assign it to me, I want to resolve this bug.

**Comment by Yash-Parsana** [comment] 2024-05-16 16:53
@Aayushraj22 this issue is assigned to you.

Steps to follow :
- First find root cause of issue, why it is happening.
- Then describe it in this thread don't jump on coding part without my approval.

**Comment by Aayushraj22** [comment] 2024-05-16 18:59
As i have overviewed the code provided, and observed that the loading state value becomes true and activePlatfrom state also changes whenever a button gets clicked and due to the state change react rerenders home component. The useEffect hooks of home component has dependency on activePlatform  also a function defined inside useEffect  which on call fetch data and make loading state to false and also assign fetched data to some state, `but when we click same button so our activeplatform state value remains same so useEffect hooks doesnot runs and loader never gets false, that is why error is error happening.`
>I think this much of info should be enough regarding this, also it would be great for me to contribute in this.

**Comment by MishraTanishq619** [comment] 2024-05-17 15:29
@Yash-Parsana and @Aayushraj22 
I can do this in one line only.

I wan to contribute aggressively for gssoc.
Please assign me and let me do this.

**Comment by Yash-Parsana** [comment] 2024-05-18 09:20
@Aayushraj22 You can start working on it.

Make sure that every thing work fine after changes. provide screen recording of working fix with PR.

**Comment by MishraTanishq619** [comment] 2024-05-18 14:15
> @Aayushraj22 You can start working on it.
> 
> Make sure that every thing work fine after changes. provide screen recording of working fix with PR.

I had provided in PR chat.
Look at my PR to see screencast.

**Closed** 2024-05-25 07:17 UTC
Labels: bug, level3, gssoc
