### ISSUE TITLE
Enhance Nav-bar

### ISSUE THREAD

**Issue by Chandu6702** [Yash-Parsana/CrazyCoderWebApp#45] opened 2024-05-18 08:13 UTC
Adding a hovering effect or animation to the buttons on the nav bar enhances the user experience.
[
![Screenshot 2024-05-18 133824](https://github.com/Yash-Parsana/CrazyCoderWebApp/assets/125206920/9694d59e-be8e-455c-85af-1eabe22b9b92)
](URL)
at present the color changes on pressing the buttons. I can enhance it by adding a hovering effect and animation.
Please Assign this to me.

**Comment by Yash-Parsana** [comment] 2024-05-18 09:36
duplicate of #9

**Closed as completed by Yash-Parsana** 2024-05-18 09:36 UTC
