### ISSUE TITLE
enhancing the styles in the footer

### ISSUE THREAD

**Issue by anshulsoni4** [Yash-Parsana/CrazyCoderWebApp#19] opened 2024-05-11 16:57 UTC

**Comment by aamna111** [comment] 2024-05-12 07:50
i can resolve this issue. pls assign this issue me under gssoc 24

**Comment by Yash-Parsana** [comment] 2024-05-16 17:02
it is duplicate of #25 You can add comment there and answer the asked question in that thread

**Closed** 2024-05-16 17:02 UTC
